title: MakerVR
email: pss@acm.org
description: >
  MakerVR is a VR-enabled application for creating 3D-printable models.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pss959.github.io/"
github_username:  pss959

# Input and output directories
source:      docs
destination: ../build/PublicDoc/site

theme: just-the-docs

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

# Theme configuration.
search_enabled: true
aux_links:  # Shown in upper right
  "MakerVR on GitHub":
    - "//github.com/pss959/MakerVR"
aux_links_new_tab: true
heading_anchors: true


# -----------------------------------------------------------------------------

# Variables used in content.
app_name: MakerVR
