# -----------------------------------------------------------------------------
# scons configuration for public documentation using Doxygen.
#
# Generates public documentation using Jekyll in the "PublicDoc/site"
# subdirectory of the build directory.
# -----------------------------------------------------------------------------

Import('doc_build_dir', 'APP_NAME', 'VERSION_STRING')

env = Environment(
    OUTPUT_DIR = f'#{doc_build_dir}/PublicDoc/site',
)

# Set up environment variables for Jekyll to access.
env.Append(
    ENV = {
        'APP_NAME'       : APP_NAME,
        'VERSION_STRING' : VERSION_STRING,
    }
)

# Recursive function to find all files under a root directory.
def FindAllSources(root_dir):
    from os      import walk
    from os.path import join
    sources = []
    for root, dirnames, filenames in walk(root_dir, topdown=True):
        # Skip directories beginning with '.'.
        [dirnames.remove(d) for d in list(dirnames) if d.startswith('.')]
        sources += [join(root, fn) for fn in filenames]
    return sources

sources = ['_config.yml', 'Gemfile'] + FindAllSources('docs')

doc = env.Command('$OUTPUT_DIR/index.html', sources,
                  ['echo = Building public doc for version: $VERSION_STRING',
                   'bundle exec jekyll build --baseurl "///home/pss/git/MakerVR/build/PublicDoc/site/"'],
                  chdir='PublicDoc')
Return('doc')
